# Generated by Django 4.1.1 on 2022-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facilities',
            field=models.ManyToManyField(help_text='Select a feature for this project', to='projects.facilities'),
        ),
    ]
