# Generated by Django 4.1.1 on 2022-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the project', max_length=1000),
        ),
    ]
