# Generated by Django 4.1.1 on 2022-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_housetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product feature (e.g. Fan Kitchen-cabinet wardropes)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='housetype',
            name='features',
            field=models.ManyToManyField(help_text='Select a feature for this product', to='projects.housefeature'),
        ),
    ]
