# Generated by Django 4.1.1 on 2022-09-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_housefeature_housetype_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility',
            new_name='ProjectFacility',
        ),
    ]
