# Generated by Django 4.1.1 on 2022-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_facility_projectfacility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housetype',
            old_name='House_floor_area',
            new_name='house_floor_area',
        ),
        migrations.RenameField(
            model_name='housetype',
            old_name='House_specification',
            new_name='house_specification',
        ),
    ]
