# Generated by Django 4.1.1 on 2022-10-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_house_floor_area_housetype_house_floor_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Others', 'Others')], default='Residential', help_text='Project purpose', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Not started', help_text='Project work status', max_length=50),
        ),
    ]
