# Generated by Django 4.1.1 on 2022-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hectares',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter the number of hectares', max_digits=6, null=True),
        ),
    ]
