# Generated by Django 4.1.1 on 2022-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_housetype_features_housetype_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetype',
            name='bath',
            field=models.PositiveBigIntegerField(default=1, help_text='Enter the Number of Bathrooms'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='bed',
            field=models.PositiveBigIntegerField(default=1, help_text='Enter the Number of Bedrooms'),
        ),
    ]
