# Generated by Django 4.1.1 on 2022-10-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_housetype_bath_housetype_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housetypes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='status',
            field=models.CharField(blank=True, choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], default='For Sale', help_text='House Type status', max_length=50),
        ),
    ]
