# Generated by Django 4.1.1 on 2022-09-28 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product feature (e.g. Fan Kitchen-cabinet wardropes)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_Document', models.CharField(blank=True, max_length=250, null=True)),
                ('specification', models.TextField(help_text='Enter a brief specification of the product', max_length=500)),
                ('location', models.TextField(help_text='Enter a the product location', max_length=250)),
                ('payment_duration', models.PositiveIntegerField(help_text='Enter a number in months e.g 18')),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('floor_area', models.PositiveBigIntegerField(help_text='Enter the net floor area for the product')),
                ('image', models.ImageField(upload_to='images/')),
                ('sales', models.CharField(blank=True, choices=[('LD', 'Land'), ('BD', 'Building')], default='NS', help_text='Product type status', max_length=2)),
                ('features', models.ManyToManyField(help_text='Select a feature for this product', to='products.features')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
