# Generated by Django 4.1.1 on 2022-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('LD', 'Land'), ('BD', 'Building')], default='BD', help_text='Product type status', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(help_text='Enter a the product location', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.CharField(blank=True, choices=[('SO', 'Sold Out'), ('NS', 'Now Selling'), ('OR', 'On Request'), ('NA', 'Not Available')], default='NS', help_text='Product sales status', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(help_text='Enter a brief specification of the product', max_length=500),
        ),
    ]
