# Generated by Django 4.1.1 on 2022-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_type_alter_product_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(help_text='Enter a the product location', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(help_text='Enter a brief specification of the product', max_length=300),
        ),
    ]
