# Generated by Django 4.1.1 on 2022-09-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_slug_alter_product_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
