# Generated by Django 4.1.1 on 2022-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_features_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installmental_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter installmental payment price', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='mortgage_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the mortgage payment price', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='outright_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the outright payment price', max_digits=12),
        ),
    ]
