# Generated by Django 4.1.1 on 2022-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='duration',
            field=models.CharField(blank=True, choices=[('AN', 'Annually'), ('MN', 'Monthly')], default='AN', help_text='Investment duration status', max_length=2),
        ),
        migrations.AlterField(
            model_name='investment',
            name='roi',
            field=models.PositiveIntegerField(help_text='Enter the ROI of investment'),
        ),
    ]
