# Generated by Django 4.1.1 on 2022-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_investment_duration_alter_investment_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='roi',
            field=models.PositiveIntegerField(help_text='Enter the Return on Investment in %'),
        ),
    ]
