# Generated by Django 4.1.1 on 2022-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_investment_description_alter_investment_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.CharField(blank=True, choices=[('Sold Out', 'Sold Out'), ('Now Selling', 'Now Selling'), ('On Request', 'On Request'), ('Not Available', 'Not Available')], default='NS', help_text='Product sales status', max_length=50),
        ),
    ]
