# Generated by Django 4.1.1 on 2022-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.CharField(blank=True, choices=[('Sold Out', 'Sold Out'), ('Now Selling', 'Now Selling'), ('On Request', 'On Request'), ('Not Available', 'Not Available')], default='Now Selling', help_text='Product sales status', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Land', 'Land'), ('Building', 'Building')], default='Building', help_text='Product type status', max_length=50),
        ),
    ]
