# Generated by Django 4.1.1 on 2022-10-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_Document',
            new_name='title_document',
        ),
    ]
