# Generated by Django 4.1.1 on 2022-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_created_remove_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
